{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:OCC.Display.backend:The qt-pyqt5 backend is already loaded...``load_backend`` can only be called once per session\n",
      "INFO:OCC.Display.SimpleGui:GUI backend set to: qt-pyqt5\n"
     ]
    }
   ],
   "source": [
    "import math\n",
    "import sys\n",
    "\n",
    "from OCC.Core.gp import (gp_Pnt, gp_Ax3, gp_Dir, gp_Circ, gp_Ax2)\n",
    "from OCC.Core.BRepBuilderAPI import (BRepBuilderAPI_MakeEdge,\n",
    "                                     BRepBuilderAPI_MakeFace,\n",
    "                                     BRepBuilderAPI_MakeWire,\n",
    "                                     BRepBuilderAPI_MakeVertex)\n",
    "from OCC.Core.TColgp import TColgp_Array1OfPnt\n",
    "from OCC.Core.Geom import Geom_BezierCurve\n",
    "from OCC.Core.Geom2d import Geom2d_Line\n",
    "\n",
    "from OCC.Display.SimpleGui import init_display\n",
    "\n",
    "#display, start_display, add_menu, add_function_to_menu = \\\n",
    "#        init_display()\n",
    "\n",
    "def Line(event=None):\n",
    "    p1 = gp_Pnt()\n",
    "    p2 = gp_Pnt()\n",
    "    \n",
    "    p1.SetCoord(-5,-5,-5)\n",
    "    p2.SetCoord(5,5,5)\n",
    "    \n",
    "    p1_vertex = BRepBuilderAPI_MakeVertex(p1)\n",
    "    p2_vertex = BRepBuilderAPI_MakeVertex(p2)\n",
    "    p1_vertex.Vertex()\n",
    "    line = BRepBuilderAPI_MakeEdge(p1_vertex.Vertex(), p2_vertex.Vertex())\n",
    "    display.DisplayColoredShape(line.Edge(), 'CYAN')\n",
    "    display.DisplayColoredShape(p1_vertex.Vertex(),'WHITE')\n",
    "    display.DisplayColoredShape(p2_vertex.Vertex(),'WHITE')\n",
    "    display.FitAll()\n",
    "\n",
    "def Disk(event=None, parent):\n",
    "    x = parent.input\n",
    "    center = gp_Pnt(0,0,0)\n",
    "    normal = gp_Dir(0,0,1)\n",
    "    radius = 10\n",
    "    circle = gp_Circ( gp_Ax2(center,normal) , radius)\n",
    "    circle_edge = BRepBuilderAPI_MakeEdge(circle)\n",
    "    circle_wire = BRepBuilderAPI_MakeWire(circle_edge.Edge())\n",
    "    circle_face = BRepBuilderAPI_MakeFace(circle_wire.Wire())\n",
    "    display.DisplayColoredShape(circle_face.Face(),'RED')\n",
    "    display.FitAll()\n",
    "    \n",
    "def Rectangle(event=None):\n",
    "    p1 = gp_Pnt()\n",
    "    p2 = gp_Pnt()\n",
    "    p3 = gp_Pnt()\n",
    "    p4 = gp_Pnt()\n",
    "    \n",
    "    p1.SetCoord(0,0,0)\n",
    "    p2.SetCoord(0,10,0)\n",
    "    p3.SetCoord(5,10,0)\n",
    "    p4.SetCoord(5,0,0)\n",
    "    \n",
    "    Edge1 = BRepBuilderAPI_MakeEdge(p1, p2)\n",
    "    Edge2 = BRepBuilderAPI_MakeEdge(p2, p3)\n",
    "    Edge3 = BRepBuilderAPI_MakeEdge(p3, p4)\n",
    "    Edge4 = BRepBuilderAPI_MakeEdge(p4, p1)\n",
    "\n",
    "    rect_wire = BRepBuilderAPI_MakeWire(Edge1.Edge(), Edge2.Edge(), Edge3.Edge(), Edge4.Edge())\n",
    "    if not rect_wire.IsDone():\n",
    "        raise AssertionError(\"rect_wire is not done.\")\n",
    "    rect_face = BRepBuilderAPI_MakeFace(rect_wire.Wire())\n",
    "    display.DisplayColoredShape(rect_face.Face(),'BLUE')\n",
    "    display.FitAll()\n",
    "    \n",
    "def Triangle(event=None):\n",
    "    p1 = gp_Pnt()\n",
    "    p2 = gp_Pnt()\n",
    "    p3 = gp_Pnt()\n",
    "    \n",
    "    p1.SetCoord(0,0,0)\n",
    "    p2.SetCoord(-5,0,0)\n",
    "    p3.SetCoord(0,-5,0)\n",
    "    \n",
    "    Edge1 = BRepBuilderAPI_MakeEdge(p1, p2)\n",
    "    Edge2 = BRepBuilderAPI_MakeEdge(p2, p3)\n",
    "    Edge3 = BRepBuilderAPI_MakeEdge(p1, p3)\n",
    "\n",
    "    tri_wire = BRepBuilderAPI_MakeWire(Edge1.Edge(), Edge2.Edge(), Edge3.Edge())\n",
    "    if not tri_wire.IsDone():\n",
    "        raise AssertionError(\"rect_wire is not done.\")\n",
    "    tri_face = BRepBuilderAPI_MakeFace(tri_wire.Wire())\n",
    "    display.DisplayColoredShape(tri_face.Face(),'YELLOW')\n",
    "    display.FitAll()\n",
    "    \n",
    "def Curve(event=None):\n",
    "    P1 = gp_Pnt(-15, 20, 10)\n",
    "    P2 = gp_Pnt(5, 20, 0)\n",
    "    P3 = gp_Pnt(15, 20, 0)\n",
    "    P4 = gp_Pnt(-15, 20, 15)\n",
    "    P5 = gp_Pnt(-5, 20, 0)\n",
    "    P6 = gp_Pnt(15, 20, 0)\n",
    "    P7 = gp_Pnt(24, 12, 0)\n",
    "    P8 = gp_Pnt(-24, 12, 12.5)\n",
    "    array = TColgp_Array1OfPnt(1, 8)\n",
    "    array.SetValue(1, P1)\n",
    "    array.SetValue(2, P2)\n",
    "    array.SetValue(3, P3)\n",
    "    array.SetValue(4, P4)\n",
    "    array.SetValue(5, P5)\n",
    "    array.SetValue(6, P6)\n",
    "    array.SetValue(7, P7)\n",
    "    array.SetValue(8, P8)\n",
    "    curve = Geom_BezierCurve(array)\n",
    "    curve_edge = BRepBuilderAPI_MakeEdge(curve)\n",
    "    display.DisplayColoredShape(curve_edge.Edge(), 'CYAN')\n",
    "    display.DisplayColoredShape(curve_edge.Vertex1(),'WHITE')\n",
    "    display.DisplayColoredShape(curve_edge.Vertex2(),'WHITE')\n",
    "    display.FitAll()\n",
    "    \n",
    "def Polygon(event=None):\n",
    "    P1 = gp_Pnt(-15, 20, 10)\n",
    "    P2 = gp_Pnt(5, 20, 0)\n",
    "    P3 = gp_Pnt(15, 20, 0)\n",
    "    P4 = gp_Pnt(-15, 20, 15)\n",
    "    P5 = gp_Pnt(-5, 20, 0)\n",
    "    P6 = gp_Pnt(15, 20, 0)\n",
    "    P7 = gp_Pnt(24, 12, 0)\n",
    "    P8 = gp_Pnt(-24, 12, 12.5)\n",
    "    array = TColgp_Array1OfPnt(1, 8)\n",
    "    array.SetValue(1, P1)\n",
    "    array.SetValue(2, P2)\n",
    "    array.SetValue(3, P3)\n",
    "    array.SetValue(4, P4)\n",
    "    array.SetValue(5, P5)\n",
    "    array.SetValue(6, P6)\n",
    "    array.SetValue(7, P7)\n",
    "    array.SetValue(8, P8)\n",
    "    curve = Geom_BezierCurve(array)\n",
    "    curve_edge = BRepBuilderAPI_MakeEdge(curve)\n",
    "    display.DisplayColoredShape(curve_edge.Edge(), 'CYAN')\n",
    "    display.DisplayColoredShape(curve_edge.Vertex1(),'WHITE')\n",
    "    display.DisplayColoredShape(curve_edge.Vertex2(),'WHITE')\n",
    "    display.FitAll()\n",
    "\n",
    "def Erase_all(event=None): \n",
    "    display.EraseAll()\n",
    "    \n",
    "def Exit(event=None):\n",
    "    sys.exit() \n",
    "\n",
    "if __name__ == '__main__': \n",
    "    # OCC.Display.SimpleGui.init_display() returns multiple \n",
    "    # values which are assigned here \n",
    "    display, start_display, add_menu, add_function_to_menu = init_display('qt')\n",
    "    # This is the place where we hook our functionality to menus \n",
    "    # ---------------------------------------------------------\n",
    "    add_menu('File') \n",
    "    add_function_to_menu('File', Exit) \n",
    "    add_menu('Draw') \n",
    "    add_function_to_menu('Draw', Line)\n",
    "    add_function_to_menu('Draw', Circle) \n",
    "    add_function_to_menu('Draw', Rectangle)\n",
    "    add_function_to_menu('Draw', Triangle)\n",
    "    add_function_to_menu('Draw', Curve)\n",
    "    add_function_to_menu('Draw', Polygon)\n",
    "    add_menu('Erase') \n",
    "    add_function_to_menu('Erase', Erase_all)\n",
    "    \n",
    "    start_display()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (myenv)",
   "language": "python",
   "name": "myenv"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
